= OpenSSH Client Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:openssh: https://www.openssh.com/[OpenSSH]

My user's {OpenSSH} client configuration.

== Usage

This repository contains the configuration files for {OpenSSH} which belong in the ~/.ssh/` directory.
This file is synchronized using this Git repository.
The following instructions detail how to use and sync this repository.

=== Install

Install these settings with the following instructions.

. Clone this repository.
+
[,sh]
----
git clone git@github.com:jwillikers/openssh-client-config.git
----

. Change to the repository directory.
+
[,sh]
----
cd openssh-client-config
----

. Create the `~/.config/ssh` and `~/.ssh/config` directories.
+
[,sh]
----
mkdir --parents ~/.config/ssh ~/.ssh
----

. Symlink the OpenSSH client configuration file to the configuration directory.
+
[,sh]
----
ln --force --relative --symbolic ssh/config ~/.ssh/config
----

. Symlink the OpenSSH client configuration directory to `~/.config/ssh/config.d`.
+
[,sh]
----
ln --force --relative --symbolic ssh/config.d ~/.config/ssh/config.d
----

== Code of Conduct

Please refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3].
Please refer to the bundled link:LICENSE.adoc[license].

== Copyright

© 2023 Jordan Williams

== Authors

mailto:{email}[{author}]
